name: 'Bill.com x Airtable Action'
description: 'Run a Javascript program that uses airtable.js and bill_com.js'
inputs:
  file-id:
    description: 'The Javascript file ID'
    required: true
  primary-org:
    description: 'The primary Bill.com Org'
    required: true
  airtable-api-key:
    description: 'The Airtable API key to use for Airtable interactions'
    required: true
  airtable-base-id:
    description: 'The ID of the Airtable Base used in the target program'
    required: true
  airtable-org-ids-base-id:
    description: 'The ID of the Airtable Base housing the Bill.com Org IDs'
    required: true
  bill-com-dev-key:
    description: 'The Bill.com developer key for API access'
    required: true
  bill-com-user-name:
    description: 'The Bill.com email for login'
    required: true
  bill-com-password:
    description: 'The Bill.com password for login'
    required: true
  internal-customer-id:
    description: 'The Parent Bill.com Customer ID for internal Customers'
    required: false
  ecr-approver-user-profile-id:
    description: 'The Bill.com User Profile ID for ECR Approvers'
    required: false
  final-approver-user-id:
    description: 'The Bill.com User ID of the final Bill Approver'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
