name: Abacus Workflow
on:
  workflow_dispatch:
    inputs:
      airtable-import-record-id:
        description: 'The ID of the Airtable Record whose CSVs shhould be parsed and integrated'
        required: true
        type: string
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: RSTechTeam/airtable-integrations/.github/actions/abacus@main
        with:
          airtable-api-key: ${{ secrets.AIRTABLE_API_KEY }}
          airtable-base-id: ${{ secrets.EXPENSE_SOURCES_BASE_ID }}
          airtable-import-record-id: ${{ inputs.airtable-import-record-id }}
