name: Main Workflow
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      # Run jobs sequentially to avoid Bill.com API's concurrent request limit:
      # 3 per Developer Key per Organization
      max-parallel: 1
      fail-fast: false
      matrix:
        file-id: [
          # Creates that don't reference other data
          'bill_com_integration_create_approver',
          'door_knocking_create_vendor',
          # Sync including newlty created data
          'bill_com_integration_sync_internal_customers',
          'bill_com_integration_sync',
          # Creates that reference synced data
          'bill_com_integration_create_bill',
          # Sync including more recently created data
          'bill_com_integration_sync_bills',
        ]
    steps:
      - id: get-airtable-base-id
        run: |
          case ${{ matrix.file-id }} in
            door_knocking*)
              id=${{ secrets.DOOR_KNOCKING_BASE_ID }}
              ;;
            *)
              id=${{ secrets.BILL_COM_INTEGRATION_BASE_ID }}
              ;;
          esac
          echo "id=$id" >> $GITHUB_OUTPUT
      - uses: RSTechTeam/Bill.com-Airtable-Integration@main
        with:
          file-id: ${{ matrix.file-id }}
          airtable-api-key: ${{ secrets.AIRTABLE_API_KEY }}
          airtable-base-id: ${{ steps.get-airtable-base-id.outputs.id }}
          airtable-org-ids-base-id: ${{ secrets.BILL_COM_INTEGRATION_BASE_ID }}
          bill-com-dev-key: ${{ secrets.BILL_COM_DEV_KEY }}
          bill-com-user-name: ${{ secrets.BILL_COM_USER_NAME }}
          bill-com-password: ${{ secrets.BILL_COM_PASSWORD }}
          ecr-approver-user-profile-id: ${{ secrets.ECR_APPROVER_USER_PROFILE_ID }}
