name: Main Workflow
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      # Run jobs sequentially to avoid Bill.com API's concurrent request limit:
      # 3 per Developer Key per Organization
      max-parallel: 1
      fail-fast: false
      matrix:
        file-id: [
          'accounting_sync',
          'bill_com_integration_sync',
          'bill_com_integration_create_bill',
          'bill_com_integration_create_approver',
        ]
        include:
          - base-id-index: 0
          - base-id-index: 1
            file-id: 'accounting_sync'
    steps:
      - id: get-airtable-base-id
        run: |
          if [ ${{ startsWith(matrix.file-id, 'accounting') }} = true ] ; then
            id=${{ secrets.ACCOUNTING_TERMINOLOGY_INDEX_BASE_ID }}
          else
            id=${{ secrets.BILL_COM_INTEGRATION_BASE_ID }}
          fi
          echo "::set-output name=id::$id"
      - uses: RSMvmtTech/Bill.com-Airtable-Integration@main
        env:
          BASE_IDS: (${{ secrets.BILL_COM_INTEGRATION_BASE_ID }} ${{ secrets.ACCOUNTING_TERMINOLOGY_INDEX_BASE_ID }})
        with:
          file-id: ${{ matrix.file-id }}
          primary-org: 'RS'
          airtable-api-key: ${{ secrets.AIRTABLE_API_KEY }}
          airtable-base-id: ${{ env.BASE_IDS[matrix.base-id-index] }}
          airtable-org-ids-base-id: ${{ secrets.BILL_COM_INTEGRATION_BASE_ID }}
          bill-com-dev-key: ${{ secrets.BILL_COM_DEV_KEY }}
          bill-com-user-name: ${{ secrets.BILL_COM_USER_NAME }}
          bill-com-password: ${{ secrets.BILL_COM_PASSWORD }}
          internal-customer-id: ${{ secrets.INTERNAL_CUSTOMER_ID }}
          ecr-approver-user-profile-id: ${{ secrets.ECR_APPROVER_USER_PROFILE_ID }}
          final-approver-user-id: ${{ secrets.FINAL_APPROVER_USER_ID }}
