name: Main Workflow
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      # Run jobs sequentially to avoid Bill.com API's concurrent request limit:
      # 3 per Developer Key per Organization
      max-parallel: 1
      fail-fast: false
      matrix:
        file-id: [
          'accounting_sync',
          'bill_com_integration_sync',
          'bill_com_integration_create_bill',
          'bill_com_integration_create_approver',
        ]
        include:
          - airtable-base-id: ${{ secrets.BILL_COM_INTEGRATION_BASE_ID }}
          - file-id: 'accounting_sync'
            airtable-base-id: ${{ secrets.ACCOUNTING_TERMINOLOGY_INDEX_BASE_ID }}
    steps:
      - uses: RSMvmtTech/Bill.com-Airtable-Integration@main
        with:
          file-id: ${{ matrix.file-id }}
          primary-org: 'RS'
          airtable-api-key: ${{ secrets.AIRTABLE_API_KEY }}
          airtable-base-id: ${{ matrix.airtable-base-id }}
          airtable-org-ids-base-id: ${{ secrets.BILL_COM_INTEGRATION_BASE_ID }}
          bill-com-dev-key: ${{ secrets.BILL_COM_DEV_KEY }}
          bill-com-user-name: ${{ secrets.BILL_COM_USER_NAME }}
          bill-com-password: ${{ secrets.BILL_COM_PASSWORD }}
          internal-customer-id: ${{ secrets.INTERNAL_CUSTOMER_ID }}
          ecr-approver-user-profile-id: ${{ secrets.ECR_APPROVER_USER_PROFILE_ID }}
          final-approver-user-id: ${{ secrets.FINAL_APPROVER_USER_ID }}
