name: Test Workflow
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.TEST_BASE_ID }}
          AIRTABLE_ORG_IDS_BASE_ID: ${{ secrets.TEST_BASE_ID }}
          BILL_COM_DEV_KEY: ${{ secrets.TEST_DEV_KEY }}
          BILL_COM_USER_NAME: ${{ secrets.BILL_COM_USER_NAME }}
          BILL_COM_PASSWORD: ${{ secrets.TEST_BILL_COM_PASSWORD }}
          APPROVER_USER_PROFILE_ID: ${{ secrets.TEST_APPROVER_USER_PROFILE_ID }}
